# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iOaWjAWy26IXvcLjXvYDAEeBL53BBIAY
"""

# Comentando esta linha

# print é para mostrar texto e informações na tela
print("Ola Mundo") # Aspas duplas
print('Oi tudo bem?') # Aspas simples

# Menu interativo
print("""
Sistemas de operações matemáticas

1) Soma:
2) Multiplicação:
3) Divisão:
4) Subtração:

Digite a opção desejada:""")
istrume = input ("digite")