# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DcxYL1XKGosTfKjiBvNXw6PaI5_nNa4O
"""

# Variaveis

pessoa1 = 10
pessoa2 = 20

print(pessoa1 + pessoa2)

pessoa1 = int( input("Digite o número de pessoas: ") )
talheres =  int( input("Digite o número de talheres por pessoa: ") )
# Converter de str/texto para número inteiro  int()

# type() comando que retorna o tipo da variável

type(pessoa1)
#str é texto
# int é inteiro
# float números reais

print(pessoa1/talheres)

# Soma +
# Subtração -
# multiplicação *
# divizão /

dogao = int( input("Quantidade de cachorro quente: ") )
valor_dogao = 6.50

print("O valor total do cachorro quente é: R$",dogao * valor_dogao)

# Exercicios

# 1) Digite 2 números e mostre (print) a soma dos números
# 2) Digite 2 números e mostre (print) a divisão dos números
# 3) Digite 2 números e mostre (print) a multiplicação dos números
# 4) Digite 2 números e mostre (print) a subtração dos números

# Assunto exercico 2
abioluz@gmail.com

# 1)
valor1 = int( input("Digite um número para a soma: ") )
valor2 = int( input('Digiete o segundo número para a soma: ') )

print(valor1 + valor2)

# 1)
valor1 = float( input("Digite um número para a soma: ") )
valor2 = float( input('Digiete o segundo número para a soma: ') )

print(valor1 + valor2)

resultado = 0
var1 = 10
var2 = 3
resultado = var1/ var2
print(resultado)

# Inteiro
int()
# Real / float / ponto flutuante
float()
# texto / string
str()

teste = float(10)
teste = str(10)
print(teste)
type(teste)

# 1)
valor1 = str( input("Digite um número para a soma: ") )
valor2 = str( input('Digiete o segundo número para a soma: ') )

print(valor1, valor2)

print("Aprete enter para sair!")
input()
print('Saiu!')

print("Digite seu nome")
nome = input()
print('Oi', nome)